// Discontinued Finishes specific data
export const DISCONTINUED_FINISHES = [
    {
        id: 1,
        oldName: 'Honey Maple',
        newName: 'Alabaster',
        category: 'Wood Veneer',
        lab: 'V-114',
        discontinuedDate: '2023-06',
        newImage: '/jsi_finish_ALB_Alabaster_Laminate.jpg',
    },
    {
        id: 2,
        oldName: 'Cherry Natural',
        newName: 'Bridal Blanco',
        category: 'Wood Veneer',
        lab: 'V-227',
        discontinuedDate: '2023-06',
        newImage: '/jsi_finish_BBL_BridalBlanco_Laminate.jpg',
    },
    {
        id: 3,
        oldName: 'Oak Golden',
        newName: 'Belair',
        category: 'Wood Veneer',
        lab: 'V-319',
        discontinuedDate: '2023-06',
        newImage: '/jsi_finish_BEL_Belair_Laminate.jpg',
    },
    {
        id: 4,
        oldName: 'Walnut Classic',
        newName: 'Florence Walnut',
        category: 'Wood Veneer',
        lab: 'V-408',
        discontinuedDate: '2022-01',
        newImage: '/jsi_finish_FLO_FlorenceWalnut_Laminate.jpg',
    },
    {
        id: 5,
        oldName: 'Ebony Matte',
        newName: 'Umber',
        category: 'Wood Veneer',
        lab: 'V-512',
        discontinuedDate: '2022-01',
        newImage: '/jsi_finish_UMB_Umber_Laminate.jpg',
    },
    {
        id: 6,
        oldName: 'Beech Light',
        newName: 'Weathered Ash',
        category: 'Wood Veneer',
        lab: 'V-631',
        discontinuedDate: '2023-06',
        newImage: '/jsi_finish_WEA_WeatheredAsh_Laminate.jpg',
    },
    {
        id: 7,
        oldName: 'White Gloss',
        newName: 'Designer White',
        category: 'Laminate',
        discontinuedDate: '2024-03',
        newImage: '/jsi_finish_DWH_DesignerWhite_Laminate.jpg',
    },
    {
        id: 8,
        oldName: 'Black Satin',
        newName: 'Black',
        category: 'Laminate',
        discontinuedDate: '2024-03',
        newImage: '/jsi_finish_BLK_Black_Laminate.jpg',
    },
    {
        id: 9,
        oldName: 'Gray Stone',
        newName: 'Slate Grey',
        category: 'Laminate',
        discontinuedDate: '2024-03',
        newImage: '/jsi_finish_SLG_SlateGrey_Laminate.jpg',
    },
    {
        id: 10,
        oldName: 'Matte Nickel',
        newName: 'Arctic Silver',
        category: 'Metal',
        discontinuedDate: '2024-09',
        newImage: '',
    },
];

export const FINISH_CATEGORIES = [
    'Wood Veneer',
    'Laminate',
    'Metal',
];